Alex branch
Calvin906/StockApp pull request #4
Opened 2016-09-21 06:19 UTC by Calvin906

Created Homepage and added two fragments to it. I had to put off this for a bit to get school under control. I will be working more steadily from now on.

2016-09-22 17:43 UTC, JPrez38 commented on app/src/main/java/preston/com/stockapp/HomeActivity.java
> +        Typeface face = Typeface.createFromAsset(getAssets(), "bondini.ttf");
this is good. I can teach you a trick that you can set the typeface in xml. You basically just have an override on a general activity. But it's a great start. Nice job.

2016-09-22 17:44 UTC, JPrez38 commented on app/src/main/java/preston/com/stockapp/HomeActivity.java
> +        signUp.setOnClickListener(new View.OnClickListener() {
Just implement the onClickListener on the activity. Use a switch(v.getId) to distinguish the specific views

2016-09-22 17:45 UTC, JPrez38 requested changes

2016-09-22 17:45 UTC, JPrez38 commented on app/src/main/java/preston/com/stockapp/util/LoginFragment.java
> +        cancel.setOnClickListener(new View.OnClickListener() {
Again implement onClickListner in the class

2016-09-22 17:46 UTC, JPrez38 commented on app/src/main/java/preston/com/stockapp/util/SignUpFragment.java
> +    public SignUpFragment() {
Shouldn't have your own constructor in fragments

2016-09-22 17:46 UTC, JPrez38 commented on app/src/main/java/preston/com/stockapp/util/SignUpFragment.java
> +        cancel.setOnClickListener(new View.OnClickListener() {
implement listener

2016-09-22 17:47 UTC, JPrez38 commented on app/src/main/res/layout/home_activity.xml
> +    <RelativeLayout
whole thing could probably be one flat relative layout

2016-09-22 17:47 UTC, JPrez38 commented on app/src/main/res/layout/login_view.xml
> +    <RelativeLayout
you don't need nested relative layouts.

2016-09-22 17:47 UTC, JPrez38 commented on app/src/main/res/layout/login_view.xml
> +    <RelativeLayout
another nested relative layout. It's slow performance.

2016-09-22 17:47 UTC, JPrez38 commented on app/src/main/res/layout/sign_up_view.xml
> +    <RelativeLayout
don't nest relative layouts

2016-09-22 17:48 UTC, JPrez38 requested changes
Some xml changes mostly. Looks pretty good.

2016-09-23 05:15 UTC, Calvin906 commented on app/src/main/java/preston/com/stockapp/HomeActivity.java
> +        Typeface face = Typeface.createFromAsset(getAssets(), "bondini.ttf");
Done

2016-09-23 05:15 UTC, Calvin906 commented on app/src/main/java/preston/com/stockapp/HomeActivity.java
> +        signUp.setOnClickListener(new View.OnClickListener() {
Done

2016-09-23 05:15 UTC, Calvin906 commented on app/src/main/java/preston/com/stockapp/util/LoginFragment.java
> +        cancel.setOnClickListener(new View.OnClickListener() {
Done

2016-09-23 05:15 UTC, Calvin906 commented on app/src/main/java/preston/com/stockapp/util/SignUpFragment.java
> +    public SignUpFragment() {
Done

2016-09-23 05:15 UTC, Calvin906 commented on app/src/main/java/preston/com/stockapp/util/SignUpFragment.java
> +        cancel.setOnClickListener(new View.OnClickListener() {
Done

2016-09-23 05:16 UTC, Calvin906 commented on app/src/main/res/layout/home_activity.xml
> +    <RelativeLayout
Done

2016-09-23 05:16 UTC, Calvin906 commented on app/src/main/res/layout/login_view.xml
> +    <RelativeLayout
Done

2016-09-23 05:16 UTC, Calvin906 commented on app/src/main/res/layout/login_view.xml
> +    <RelativeLayout
Done

2016-09-23 05:16 UTC, merged